// RightsPortalView.swift — in-app DPDPA Rule 14 rights portal (Week 4).
//
// PURPOSE
// ───────
// Native SwiftUI form that lets a data principal file a DSAR (access,
// correction, erasure, portability, objection, withdrawal, nomination)
// directly inside the host app. Posts to the same slug-routed public
// endpoint the web rights portal uses
// (`POST /v1/dsar-requests/public/<tenantSlug>`) via the verified
// `RightsService.fileDSAR()`.
//
// RULE 14 ALIGNMENT
// ─────────────────
// DPDPA Rule 14(1)(b) requires the Data Fiduciary to publish the
// identifier(s) it needs to fulfil a request. Rule 14(5) defines the
// identifier as a SET keyed by name (customerId, email, mobile, etc.) —
// NOT a uniform UUID. This view collects the most common identifiers
// (email + optional mobile + optional customer ID) plus the request
// type; the backend resolves the principal via the Integration Hub's
// `principal_lookup` connector capability against the customer's CRM.
//
// LOCALIZATION
// ────────────
// All static strings resolve via the SDK's bundled .lproj resources
// (23 languages, generated by `scripts/sync-sdk-translations.ts` from
// `packages/sdk/src/banner/translations.ts`). No runtime translation;
// no English placeholders. The `rights_portal_title` and
// `rights_portal_subtitle` keys mirror the entrypoint copy in the
// preference center.
//
// USAGE
// ─────
// Presented as a sheet from the preference center's "Submit a privacy
// request" row OR launched directly from the host app's menu. On
// `.submitted(referenceNumber)`, the host should dismiss this view AND
// the preference center if it was the parent.

#if canImport(SwiftUI)
import SwiftUI
#endif

#if canImport(UIKit)
import UIKit
#endif

#if canImport(SwiftUI) && canImport(UIKit)

// MARK: - RightsPortalDecision

/// Outcome of the rights portal form.
public enum RightsPortalDecision: Equatable, Sendable {
    /// User filed the request. The reference number is the
    /// `DSAR-YYYY-NNNN` string returned by the backend; the host
    /// should surface it (e.g. "Your request DSAR-2026-0089 has been
    /// received") and may navigate to a status page.
    case submitted(referenceNumber: String)
    /// User tapped Cancel / Back without submitting.
    case cancelled
}

// MARK: - RightsPortalView

/// Native SwiftUI rights portal.
///
/// - Parameters:
///   - domain: Same domain key passed to BannerView. Used for theme
///     resolution + analytics tagging only — the actual submission is
///     scoped to the configured tenantSlug.
///   - config: Already-loaded WidgetConfig if available (so the form
///     inherits the parent banner's theme). Pass `nil` to fall back to
///     platform defaults.
///   - prefilledEmail: Optional. Pre-fills the email field — host apps
///     that already know the signed-in user's email should pass it so
///     the user doesn't have to retype.
///   - onDone: Called once the user has submitted or cancelled.
@available(iOS 15.0, *)
public struct RightsPortalView: View {
    private let domain: String
    private let config: WidgetConfig?
    private let rightsPortalConfig: RightsPortalWidgetConfig?
    private let prefilledEmail: String?
    private let onDone: (RightsPortalDecision) -> Void

    // ── Form state ──────────────────────────────────────────────
    /// Request type selector (Picker). Default `.erasure` matches the
    /// most-requested DPDPA right under R.14.
    @State private var requestType: RequestType = .erasure
    /// Dynamic identifier map — one entry per tenant-required key.
    /// Seeded from `rightsPortalConfig.identifiers` in init; falls back
    /// to the generic `email` / `mobile` / `customerId` triple when no
    /// config is provided (e.g. backward compatibility with v0.1.0-beta.1
    /// integrations that don't fetch the widget config).
    @State private var identifierValues: [String: String] = [:]
    /// Free-form context for the request. Optional, but recommended
    /// for correction / objection where the data principal needs to
    /// explain what they want changed.
    @State private var description: String = ""

    @State private var inFlight: Bool = false
    @State private var error: String?

    /// Effective identifier list — either the tenant's per-config set
    /// or the generic fallback. Computed once at init via the State
    /// seeding pattern.
    private let identifiers: [RightsPortalIdentifier]

    public init(
        domain: String,
        config: WidgetConfig? = nil,
        rightsPortalConfig: RightsPortalWidgetConfig? = nil,
        prefilledEmail: String? = nil,
        onDone: @escaping (RightsPortalDecision) -> Void
    ) {
        self.domain = domain
        self.config = config
        self.rightsPortalConfig = rightsPortalConfig
        self.prefilledEmail = prefilledEmail
        self.onDone = onDone

        // Resolve identifier list:
        //   1. If the tenant's RightsPortalWidgetConfig was fetched,
        //      use its `identifiers` array (DPDPA Rule 14(5) — each
        //      tenant defines their own identifier set).
        //   2. Otherwise fall back to the generic email/mobile/customerId
        //      triple from v0.1.0-beta.1 — keeps backward compatibility
        //      but won't match enterprise tenants. The customer's
        //      integration code should always fetch the config first.
        let resolved: [RightsPortalIdentifier]
        if let cfg = rightsPortalConfig, !cfg.identifiers.isEmpty {
            resolved = cfg.identifiers
        } else {
            resolved = [
                RightsPortalIdentifier(
                    key: "email",
                    label: "Email address",
                    helpText: nil,
                    required: false
                ),
                RightsPortalIdentifier(
                    key: "mobile",
                    label: "Mobile number",
                    helpText: nil,
                    required: false
                ),
                RightsPortalIdentifier(
                    key: "customerId",
                    label: "Customer ID",
                    helpText: nil,
                    required: false
                ),
            ]
        }
        self.identifiers = resolved

        // Seed identifier values with prefilled email when present.
        // Use the first key whose label looks email-like (or fall back
        // to the literal `email` key for backward compat).
        var seeded: [String: String] = [:]
        for ident in resolved { seeded[ident.key] = "" }
        if let prefill = prefilledEmail, !prefill.isEmpty {
            if let emailKey = resolved.first(where: {
                $0.key.lowercased().contains("email") ||
                $0.label.lowercased().contains("email")
            })?.key {
                seeded[emailKey] = prefill
            }
        }
        _identifierValues = State(initialValue: seeded)
    }

    public var body: some View {
        let theme = config.map { BannerTheme.from($0) }
            ?? BannerTheme.platformDefaults
        return NavigationView {
            Form {
                headerSection(theme: theme)
                requestTypeSection
                identifierSection
                descriptionSection
                if let err = error {
                    Section { Text(err).foregroundColor(.red).font(.footnote) }
                }
                submitSection(theme: theme)
            }
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button(action: { onDone(.cancelled) }) {
                        Text(localized("foctta_button_close"))
                    }
                }
            }
        }
        .navigationViewStyle(.stack)
    }

    // MARK: - Sections

    private func headerSection(theme _: BannerTheme) -> some View {
        Section {
            VStack(alignment: .leading, spacing: 6) {
                Text(localized("foctta_rights_portal_title"))
                    .font(.headline)
                Text(localized("foctta_rights_portal_subtitle"))
                    .font(.subheadline)
                    .foregroundColor(.secondary)
            }
            .padding(.vertical, 4)
        }
    }

    /// Picker for the seven DPDPA request types. We localise the label
    /// each user sees against the bundle (`foctta_request_type_<key>`)
    /// — when those keys aren't in the .strings file yet, NSLocalizedString
    /// returns the key itself, which is more honest than a hand-rolled
    /// English fallback (and surfaces the gap during translation review).
    private var requestTypeSection: some View {
        Section {
            Picker(selection: $requestType, label: Text(localized("foctta_rights_portal_request_type_label"))) {
                ForEach(RequestType.allCases, id: \.self) { type in
                    Text(requestTypeLabel(type)).tag(type)
                }
            }
        }
    }

    /// Renders one TextField per `RightsPortalIdentifier` returned by
    /// the tenant's widget-config. When no config is present, the
    /// generic fallback identifiers (email/mobile/customerId) are
    /// rendered via the same loop.
    ///
    /// Keyboard hints are derived from the identifier's `key` /
    /// `label` so the right keyboard appears for known shapes —
    /// emailAddress → .emailAddress, phoneNumber/mobile →
    /// .phonePad, everything else → default.
    private var identifierSection: some View {
        Section(header: Text(localized("foctta_rights_portal_identifiers_header"))) {
            ForEach(identifiers) { ident in
                identifierField(for: ident)
            }
        }
    }

    @ViewBuilder
    private func identifierField(for ident: RightsPortalIdentifier) -> some View {
        let binding = Binding<String>(
            get: { identifierValues[ident.key] ?? "" },
            set: { identifierValues[ident.key] = $0 }
        )
        VStack(alignment: .leading, spacing: 2) {
            TextField(ident.label + (ident.required ? " *" : ""), text: binding)
                .keyboardType(keyboardType(for: ident))
                .textContentType(contentType(for: ident))
                .autocapitalization(autocapitalization(for: ident))
                .disableAutocorrection(shouldDisableAutocorrect(for: ident))
            if let help = ident.helpText, !help.isEmpty {
                Text(help)
                    .font(.caption2)
                    .foregroundColor(.secondary)
            }
        }
    }

    private func keyboardType(for ident: RightsPortalIdentifier) -> UIKeyboardType {
        let k = ident.key.lowercased()
        let l = ident.label.lowercased()
        if k.contains("email") || l.contains("email") { return .emailAddress }
        if k.contains("phone") || k.contains("mobile") ||
           l.contains("phone") || l.contains("mobile") { return .phonePad }
        return .default
    }

    private func contentType(for ident: RightsPortalIdentifier) -> UITextContentType? {
        let k = ident.key.lowercased()
        if k.contains("email") { return .emailAddress }
        if k.contains("phone") || k.contains("mobile") { return .telephoneNumber }
        return nil
    }

    private func autocapitalization(for ident: RightsPortalIdentifier) -> UITextAutocapitalizationType {
        let k = ident.key.lowercased()
        if k.contains("email") || k.contains("phone") || k.contains("mobile") {
            return .none
        }
        return .sentences
    }

    private func shouldDisableAutocorrect(for ident: RightsPortalIdentifier) -> Bool {
        let k = ident.key.lowercased()
        return k.contains("email") || k.contains("phone") || k.contains("mobile") ||
               k.contains("id") || k.contains("cif") || k.contains("pan")
    }

    private var descriptionSection: some View {
        Section(header: Text(localized("foctta_rights_portal_description_header"))) {
            // TextEditor for multi-line; Form auto-expands the row.
            TextEditor(text: $description)
                .frame(minHeight: 80)
        }
    }

    private func submitSection(theme: BannerTheme) -> some View {
        Section {
            Button(action: submit) {
                HStack {
                    Spacer()
                    if inFlight {
                        ProgressView()
                            .tint(theme.buttonTextColor)
                    } else {
                        Text(localized("foctta_rights_portal_submit"))
                            .fontWeight(.semibold)
                    }
                    Spacer()
                }
            }
            .disabled(inFlight || !isFormValid)
            .listRowBackground(isFormValid ? theme.primaryColor : Color.gray.opacity(0.3))
            .foregroundColor(theme.buttonTextColor)
        }
    }

    // MARK: - Validation

    /// Two-tier validation per DPDPA Rule 14(1)(b) + Rule 14(5):
    ///   • Every identifier marked `required: true` in the tenant's
    ///     widget-config MUST have a non-empty value.
    ///   • If the tenant has no required identifiers (rare), at least
    ///     ONE identifier overall must be populated.
    private var isFormValid: Bool {
        let requiredKeys = identifiers.filter { $0.required }.map { $0.key }
        if !requiredKeys.isEmpty {
            return requiredKeys.allSatisfy {
                !(identifierValues[$0] ?? "")
                    .trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            }
        }
        return identifierValues.values.contains {
            !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        }
    }

    // MARK: - Submit

    private func submit() {
        guard isFormValid, !inFlight else { return }
        inFlight = true
        error = nil

        // Build the identifier set per Rule 14(5) — only include fields
        // the user filled in, so the backend's principal_lookup doesn't
        // receive empty-string identifiers that could match unintended
        // records. Keys come from the tenant's widget-config exactly.
        var submittedIdentifiers: [String: String] = [:]
        for ident in identifiers {
            let value = (identifierValues[ident.key] ?? "")
                .trimmingCharacters(in: .whitespacesAndNewlines)
            if !value.isEmpty {
                submittedIdentifiers[ident.key] = value
            }
        }

        // Find the email value for the requester contact (server
        // requires `requesterContactEmail`). Look for a key that
        // matches "email" — works for both generic and per-tenant
        // (Motilal's `emailAddress`) shapes.
        let emailValue: String? = submittedIdentifiers.first {
            $0.key.lowercased().contains("email")
        }?.value
        // Similarly for mobile / phone.
        let mobileValue: String? = submittedIdentifiers.first {
            let k = $0.key.lowercased()
            return k.contains("phone") || k.contains("mobile")
        }?.value

        let trimmedDescription = description.trimmingCharacters(in: .whitespacesAndNewlines)

        Task {
            do {
                let service = FOCTTA.rights
                let result = try await service.fileDSAR(
                    requestType: requestType,
                    identifiers: submittedIdentifiers,
                    description: trimmedDescription.isEmpty ? nil : trimmedDescription,
                    contactEmail: emailValue,
                    contactMobile: mobileValue
                )
                await MainActor.run {
                    inFlight = false
                    onDone(.submitted(referenceNumber: result.dsar.referenceNumber))
                }
            } catch {
                await MainActor.run {
                    self.inFlight = false
                    // Surface the localized offline message — same key the
                    // banner uses for offline-queue errors, since DSAR
                    // submission failures fall into the same UX bucket
                    // (queued for retry once connectivity returns).
                    self.error = localized("foctta_error_offline_will_retry")
                }
            }
        }
    }

    // MARK: - i18n

    /// All 23 languages are bundled in `.lproj` resources at build time.
    private func localized(_ key: String) -> String {
        NSLocalizedString(key, bundle: .module, comment: "")
    }

    /// Picker label for each `RequestType`. Falls back to capitalised
    /// raw value if the localised key isn't in the bundle yet — the key
    /// is the source of truth, so missing strings surface visibly during
    /// translation review.
    private func requestTypeLabel(_ type: RequestType) -> String {
        let key = "foctta_request_type_\(type.rawValue)"
        let localized = NSLocalizedString(key, bundle: .module, comment: "")
        return localized == key ? type.rawValue.capitalized : localized
    }
}

@available(iOS 15.0, *)
extension BannerTheme {
    /// Standalone defaults for views (e.g. RightsPortalView launched
    /// before WidgetConfig has loaded) that don't have a config to read
    /// colors from.
    static var platformDefaults: BannerTheme {
        BannerTheme(
            primaryColor: .accentColor,
            textColor: .primary,
            buttonTextColor: .white,
            backgroundColor: Color(uiColor: .systemBackground),
            borderColor: Color(uiColor: .separator)
        )
    }
}

// MARK: - UIKit wrapper

/// Wrap [RightsPortalView] for UIKit hosting apps. Same pattern as
/// [BannerViewController] and [PreferenceCenterViewController].
@available(iOS 15.0, *)
public final class RightsPortalViewController: UIHostingController<RightsPortalView> {
    public init(
        domain: String,
        config: WidgetConfig? = nil,
        rightsPortalConfig: RightsPortalWidgetConfig? = nil,
        prefilledEmail: String? = nil,
        onDone: @escaping (RightsPortalDecision) -> Void = { _ in }
    ) {
        super.init(
            rootView: RightsPortalView(
                domain: domain,
                config: config,
                rightsPortalConfig: rightsPortalConfig,
                prefilledEmail: prefilledEmail,
                onDone: { _ in }
            )
        )
        self.rootView = RightsPortalView(
            domain: domain,
            config: config,
            rightsPortalConfig: rightsPortalConfig,
            prefilledEmail: prefilledEmail
        ) { [weak self] decision in
            onDone(decision)
            self?.dismiss(animated: true)
        }
    }

    @MainActor required dynamic init?(coder _: NSCoder) {
        fatalError("init(coder:) is not supported")
    }
}

#endif
